export const FETCH_CARTS = "FETCH_CART";
export type FETCH_CARTS = typeof FETCH_CARTS;

export const FETCH_CARTS_SUCCESS = "FETCH_CARTS_SUCCESS";
export type FETCH_CARTS_SUCCESS = typeof FETCH_CARTS_SUCCESS;

export const FETCH_CART = "FETCH_CART";
export type FETCH_CART = typeof FETCH_CART;

export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export type FETCH_CART_SUCCESS = typeof FETCH_CART_SUCCESS;

export const FETCH_USER = "FETCH_USER";
export type FETCH_USER = typeof FETCH_USER;

export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export type FETCH_USER_SUCCESS = typeof FETCH_USER_SUCCESS;

export const FETCH_USER_WITH_NAME = "FETCH_USER_WITH_NAME";
export type FETCH_USER_WITH_NAME = typeof FETCH_USER_WITH_NAME;

export const FETCH_USER_WITH_NAME_SUCCESS = "FETCH_USER_WITH_NAME_SUCCESS";
export type FETCH_USER_WITH_NAME_SUCCESS = typeof FETCH_USER_WITH_NAME_SUCCESS;
